site_name: Automation Primer
nav:
  - Home: index.md
  - WSL/VS Code: wsl_vscode.md
  - netbox-docker: netbox_docker.md

theme:
  name: material
  pallette:
    scheme: default
  features:
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
